version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/house-manager
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
    command: yarn dev
    # --- Production config ---
    # environment:
    #   - NODE_ENV=production
    #   - MONGO_URL=mongodb://mongo:27017/house-manager
    # volumes:
    #   # Remove volumes for production to avoid overwriting built files
    #   # - ./server:/app
    #   # - /app/node_modules
    # command: yarn prod
  web:
    build: ./web
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./web:/app
      - /app/node_modules
    command: yarn dev
    # --- Production config ---
    # environment:
    #   - NODE_ENV=production
    # volumes:
    #   # Remove volumes for production to avoid overwriting built files
    #   # - ./web:/app
    #   # - /app/node_modules
    # command: yarn build && yarn preview
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
